Add controllers
Kamatari-rin/java-shareit pull request #1
Opened 2023-07-02 21:15 UTC by Kamatari-rin

2023-07-03 06:08 UTC, krylov-sergey-sergeevich requested changes
Привет, в целом неплохая работа, давай поправим то что отметил и еще пару моментов:

1. Учесть и поправить нейминг методов: get - это или получение объекта или исключение, find - это или объект или null
2. Перебарщивать с Optional не вижу смысла, давай или возвращать объект или кидать исключение где нужно, а где нужна именно непределенность там уже Optional
3. В методах контроллера везде рекомендую добавить логи

Буду ждать с правками =)

2023-07-03 06:08 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    @NotNull(message = "Поле не может быть пыстым.")
лучше на англ в таких аннотациях писать

2023-07-03 06:08 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +        return owner.toBuilder().build();
А для чего так?

2023-07-03 06:08 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +public interface ItemService {
Старайся делать порядок полей в едином стиле, например пусть первым всегда идет userId а далее другие поля, так легче будет разрабатывать

2023-07-03 06:08 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/item/service/impl/ItemServiceImpl.java
> +                new UserNotFoundException(String.format("Пользователь %d не найден.", userId)));
Давай создадим специальное исключение UserFoundException наследника NotFoundException и сделаем так чтобы каждый раз не повторять текст:
`() -> new UserFoundException(userId));`

*p.s для остальных исключений тоже можно подумать в эту сторону ...*

2023-07-03 07:37 UTC, Kamatari-rin commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    @NotNull(message = "Поле не может быть пыстым.")
Ну я до этого тоже на английском писал. А потом на хардвебинаре сказали что учитывайте для какого вы рынка разрабатываете.

2023-07-03 07:40 UTC, Kamatari-rin commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +        return owner.toBuilder().build();
Вначале немного другая структура класса была и из-за этого была проблема с Lombok и заработало почему-то только так. 

Сейчас убрал, вроде работает.

2023-07-03 07:53 UTC, Kamatari-rin commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +public interface ItemService {
Принял и поправил.

2023-07-03 09:03 UTC, Kamatari-rin commented on src/main/java/ru/practicum/shareit/item/service/impl/ItemServiceImpl.java
> +                new UserNotFoundException(String.format("Пользователь %d не найден.", userId)));
Сделал, но не уверен что правильно. Не понял смысла в создании родительского класса для исключений. Как я понял вы предлагаете создать исключение NotFoundException и от него два наследника UserFoundException и ItemFoundException, но что это даст и как это использовать я не понял. Написал свою реализацию поправьте.

2023-07-03 09:09 UTC, Kamatari-rin commented on src/main/java/ru/practicum/shareit/item/service/impl/ItemServiceImpl.java
> +                new UserNotFoundException(String.format("Пользователь %d не найден.", userId)));
И еще не совсем понял почему логи нужно добавлять именно в контроллерах? 
Допустим метод     
@GetMapping("/{itemId}")
    public ResponseEntity<ItemDto> getItemById(@RequestHeader(REQUEST_HEADER_USER_ID) Long userId,
                                               @PathVariable Long itemId) {
       // Тут мы же можем только вывести информацию о том что пользователь userId запросил вещь itemId
       // Но если что-то подет не так в сервисном или слое репозитория мы же не увидим это в логах.
        log.info()
        return new ResponseEntity<ItemDto>(itemService.getItemById(userId, itemId), HttpStatus.OK);
    }

2023-07-04 07:29 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/item/service/impl/ItemServiceImpl.java
> +                new UserNotFoundException(String.format("Пользователь %d не найден.", userId)));
Логи должны быть на всех слоях, много логов не бывает. У каждого слоя логов своя задача у тех которые в контроллере просто показать что запрос дошел и он выглядит так и так. У сервиса что вот есть такая задача с такими параметрами в репозитории что мы идем в бд за такими данными

2023-07-04 07:37 UTC, krylov-sergey-sergeevich approved these changes
Привет, вижу исключении и правки - все хорошо, зачет!

2023-07-04 07:37 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/exception/NotFoundException.java
> +public class NotFoundException extends RuntimeException {
Да хорошо сделано

2023-07-07 08:40 UTC, merged