Sprint 14 all done probably
Kamatari-rin/java-shareit pull request #2
Opened 2023-07-19 10:59 UTC by Kamatari-rin

2023-07-20 13:13 UTC, krylov-sergey-sergeevich requested changes
Привет, неплохо, но давай поправим мелочи

2023-07-20 13:13 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/booking/service/impl/BookingServiceImpl.java
> +        User user = userRepository.findById(userId).orElseThrow(
Повторяется, давай сделаем метод отдельный

2023-07-20 13:13 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/booking/service/impl/BookingServiceImpl.java
> +        LocalDateTime timeNow = LocalDateTime.now();
Рекомендую создать свой класс DateUtils и через него делать все действия с датой

2023-07-20 13:13 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/booking/service/impl/BookingServiceImpl.java
> +        Booking booking = bookingRepository.findById(bookingId).orElseThrow(
дублируется

2023-07-20 13:13 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/config/BeanConfig.java
> +        return Server.createTcpServer("-tcp", "-tcpAllowOthers", "-tcpPort", "9090");
Поясни зачем это?

2023-07-20 13:13 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/item/dto/ItemResponseDto.java
> +    private Set<CommentResponseDto> comments;
Сет? А не лист? Нам порядок наверно важен коственно

2023-07-20 13:13 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/util/Constant.java
Comparator - я бы вынес в отдельный класс

2023-07-20 13:13 UTC, krylov-sergey-sergeevich commented on src/main/resources/schema.sql
> +    CONSTRAINT PK_ITEM PRIMARY KEY (id)
CONSTRAINT pk_item PRIMARY KEY (item_id),
  CONSTRAINT FK_ITEM_ON_OWNER FOREIGN KEY (owner_id) REFERENCES users (user_id),
  CONSTRAINT UQ_OWNER_ITEM_NAME UNIQUE(owner_id, name)

2023-07-20 13:13 UTC, krylov-sergey-sergeevich commented on src/main/resources/schema.sql
> +    CONSTRAINT PK_BOOKING PRIMARY KEY (id)
CONSTRAINT pk_booking PRIMARY KEY (booking_id),
  CONSTRAINT FK_BOOKING_ON_BOOKER FOREIGN KEY (booker_id) REFERENCES users (user_id),
  CONSTRAINT FK_BOOKING_ON_ITEM FOREIGN KEY (item_id) REFERENCES items (item_id)

2023-07-20 13:13 UTC, krylov-sergey-sergeevich commented on src/main/resources/schema.sql
> +    CONSTRAINT PK_COMMENT PRIMARY KEY (id)
CONSTRAINT pk_comment PRIMARY KEY (comment_id),
  CONSTRAINT FK_COMMENT_ON_AUTHOR FOREIGN KEY (author_id) REFERENCES users (user_id),
  CONSTRAINT FK_COMMENT_ON_ITEM FOREIGN KEY (item_id) REFERENCES items (item_id)

2023-07-20 13:25 UTC, Kamatari-rin commented on src/main/java/ru/practicum/shareit/config/BeanConfig.java
> +        return Server.createTcpServer("-tcp", "-tcpAllowOthers", "-tcpPort", "9090");
Сделано чтобы была возможность параллельной работы с бд в IDEA. Иначе при запущенном приложении доступ к бд блокируется.

2023-07-20 13:25 UTC, Kamatari-rin commented on src/main/java/ru/practicum/shareit/item/dto/ItemResponseDto.java
> +    private Set<CommentResponseDto> comments;
Действительно в ТЗ не важен, но вполне может понадобиться в будущем, поэтому решил сразу сделать Set.

2023-07-20 13:26 UTC, Kamatari-rin commented on src/main/resources/schema.sql
> +    CONSTRAINT PK_ITEM PRIMARY KEY (id)
Исправить не проблема, но почему нельзя делать как сделал я?

2023-07-20 13:26 UTC, Kamatari-rin commented on src/main/java/ru/practicum/shareit/booking/service/impl/BookingServiceImpl.java
> +        LocalDateTime timeNow = LocalDateTime.now();
Принял к сведению. Но тут не так много мест где требуется работа со временем, а так же нет каких-то сложных громоздских конструкций вынесение в отдельный класс которых бы повысило читаемость кода.

Оставил как есть, но если в будущем будет больше, то обязательно вынесу.

2023-07-20 13:40 UTC, Kamatari-rin commented on src/main/java/ru/practicum/shareit/booking/service/impl/BookingServiceImpl.java
> +        User user = userRepository.findById(userId).orElseThrow(
Сделал

2023-07-20 13:41 UTC, Kamatari-rin commented on src/main/java/ru/practicum/shareit/booking/service/impl/BookingServiceImpl.java
> +        Booking booking = bookingRepository.findById(bookingId).orElseThrow(
Поправил

2023-07-20 13:45 UTC, Kamatari-rin commented on src/main/java/ru/practicum/shareit/util/Constant.java
Вынес

2023-07-20 19:52 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/item/dto/ItemResponseDto.java
> +    private Set<CommentResponseDto> comments;
так а почему сет а не лист, в листе же порядок

2023-07-20 20:17 UTC, Kamatari-rin commented on src/main/java/ru/practicum/shareit/item/dto/ItemResponseDto.java
> +    private Set<CommentResponseDto> comments;
Да. Наверно в ResponseDto стоит сделать SortedSet. Из-за того что в тз требований не было по этому поводу. В Модели мне показалось логично сделать Set для того что бы избежать дублирования комментариев. Но для возвращаемого объекта наверно необходима возможность сортировки.

2023-07-20 20:40 UTC, Kamatari-rin commented on src/main/java/ru/practicum/shareit/item/dto/ItemResponseDto.java
> +    private Set<CommentResponseDto> comments;
Исправил

2023-07-21 07:09 UTC, krylov-sergey-sergeevich approved these changes
Привет, вижу правки - зачет!

2023-07-22 18:25 UTC, merged