Add item requests
Kamatari-rin/java-shareit pull request #3
Opened 2023-08-04 09:06 UTC by Kamatari-rin

2023-08-05 11:50 UTC, krylov-sergey-sergeevich requested changes
Привет, в целом неплохо пару буквально вопросов и будет засчитывать

2023-08-05 11:50 UTC, krylov-sergey-sergeevich commented on pom.xml
> +			<artifactId>commons-lang3</artifactId>
Для чего зависимость?

2023-08-05 11:50 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/request/dto/RequestCreateDto.java
> +public class RequestCreateDto {
Модификаторы доступа

2023-08-05 11:50 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/request/model/Request.java
> +    private Set<Item> items;
Почему сет? Я бы порекомендовал бы лист использовать

2023-08-05 11:50 UTC, krylov-sergey-sergeevich commented on src/main/resources/schema.sql
> +    CONSTRAINT FK_REQUESTS_ON_USER FOREIGN KEY (request_maker_id) REFERENCES users (id) ON DELETE CASCADE
каскады нам точно нужны?

2023-08-05 15:19 UTC, Kamatari-rin commented on src/main/resources/schema.sql
> +    CONSTRAINT FK_REQUESTS_ON_USER FOREIGN KEY (request_maker_id) REFERENCES users (id) ON DELETE CASCADE
Не уверен что нужны в рамках данного проекта. В теории честно говоря не помню что бы было про их правильное или не правильное применение. Из информации из сторонних источников мне показалось логично использовать каскад, так как много зависимостей и если нужно будет удалять данные, то с каскадом это будет сделать проще. 

Есть какая-то причина почему так делать не стоит?

2023-08-05 15:23 UTC, Kamatari-rin commented on src/main/java/ru/practicum/shareit/request/model/Request.java
> +    private Set<Item> items;
Почему лист? В модели я использую Set, в DTO же которое я отдаю наружу используется SortedSet, так что там порядок будет который нужен и без повторов. 

Хотя да, в принципе можно и List сделать я не думаю что тут это критично. Если критично, то напишите в чем могут быть проблемы с такой реализацией?

2023-08-05 15:24 UTC, Kamatari-rin commented on src/main/java/ru/practicum/shareit/request/dto/RequestCreateDto.java
> +public class RequestCreateDto {
+ забыл

2023-08-05 15:30 UTC, Kamatari-rin commented on pom.xml
> +			<artifactId>commons-lang3</artifactId>
Это для тестов было нужно (вроде) если я правильно помню там assertThat без нее не работал.

2023-08-06 10:56 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/request/model/Request.java
> +    private Set<Item> items;
Есть некоторые нюансы с сетом + хэшкоды + хибер, в целом сложная тема. Краткий факт в том что с листом обычно меньше проблем

2023-08-06 10:57 UTC, krylov-sergey-sergeevich commented on src/main/resources/schema.sql
> +    CONSTRAINT FK_REQUESTS_ON_USER FOREIGN KEY (request_maker_id) REFERENCES users (id) ON DELETE CASCADE
Мы переносим логику удаления с бэка на бд и это иногда легко забыть и может каскад удалить слишком много лишнего

2023-08-06 10:57 UTC, krylov-sergey-sergeevich approved these changes
Привет, вижу правки - зачет!

2023-08-06 11:03 UTC, merged